### ISSUE TITLE
How to compute tumor abundance?

### ISSUE THREAD

**Issue by zhaoxiaofei** [ParkerICI/tesla#1]
I tried computing tumor abundance (in terms of TPM, transcript per million) using kallisto, and my result looks very different compared with the result posted at https://doi.org/10.1016/j.cell.2020.09.015 Table S4. I am wondering if you have any idea about such discrepancy?

I read the paper thoroughly and I did not find any detail about the computation of tumor abundance. I also tried contacting the two corresponding authors of the paper by email, and unfortunately their email addresses are not available to receive emails.
 
I tried reproducing the binding affinity, agretopicity, foreignness and tumor abundance listed in the supplementary material of the paper. So far, binding affinity, agretopicity and foreignness can be reproduced very well. However, tumor abundance lacks the necessary detail to be reproduced.

**Comment by dannykwells** [comment]
HI XiaoFei,

Tumor abundance was calculated as the average of the abundance values
provided by each TESLA participant, for that called mutation / neoantigen.
As TESLA, we did not make determinations as to the appropriate approach, we
used what was provided by our participants (as we did for mutation calls).

Best,
d

**Comment by zhaoxiaofei** [comment]
Hi @dannykwells 

Thank you for your prompt answer.
If I understood correctly, the value of NA for tumor abundance means that none of the participants provided any abundance estimate?

**Comment by dannykwells** [comment]
Yes

**Comment by zhaoxiaofei** [comment]
Thank you for your confirmation! I will close this issue.
